name: CI Build & Push

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 17riya/yourapp:${{ github.sha }}

      - name: Update Deployment Image
        run: |
          sed -i "s|image: .*|image: 17riya/yourapp:${{ github.sha }}|" k8s/deployment.yaml

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag" || echo "No changes to commit"
          git push